<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Authors>しんかい｜Gemini</Authors>
    <Product>STSC アプリ</Product>
    <Version>1.0.0</Version>
    <Description>しんかい信号制作株式会社の公式アプリ</Description>
    <FileVersion>1.0.0</FileVersion>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <NeutralLanguage>ja</NeutralLanguage>
    <Copyright>Copyright © 2026 しんかい信号制作株式会社. All rights reserved.</Copyright>
    <PackageIcon></PackageIcon>
    <Company>しんかい信号制作株式会社</Company>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ApplicationIcon>STSC_128.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Recycle.wav" />
    <None Remove="STSC_CATALOG.png" />
    <None Remove="STSC_HOME.png" />
    <None Remove="STSC_INQUIRY.png" />
    <None Remove="STSC_NEWS.png" />
    <None Remove="しんかい信号制作株式会社.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="STSC_128.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Recycle.wav" />
    <Resource Include="STSC_CATALOG.png" />
    <Resource Include="STSC_HOME.png" />
    <Resource Include="STSC_INQUIRY.png" />
    <Resource Include="STSC_NEWS.png" />
    <Resource Include="しんかい信号制作株式会社.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AppSettings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppSettings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="AppSettings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>AppSettings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
